devops : docker-compose.prod build context changed
docker-compose.prod build context changed because of Error

ERROR: The Compose file is invalid because:
Service app has neither an image nor a build context specified. At least one must be provided.